### ISSUE TITLE
Error with flag --always-copy

### ISSUE THREAD

**Issue by jhg-tgu** [mjpizz/node-virtualenv#11]
```python
Installing setuptools, pip, wheel...
  Complete output from command /...rtualenv/bin/python2 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/lib64/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: No module named _io
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "virtualenv.py", line 2328, in <module>
    main()
  File "virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "virtualenv.py", line 945, in create_environment
    download=download,
  File "virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /...rtualenv/bin/python2 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /usr/bin/python2
Error: Error while creating virtualenv: exit 1
    at VirtualEnv.<anonymous> (/.../node_modules/virtualenv/lib/virtualenv.js:243:31)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by jhg-tgu** [comment]
Also I tried to copy the _io.so but when I run virtualenv-postintall it delete the .so file.

**Comment by jhg-tgu** [comment]
Error: EACCES: permission denied, unlink '/.../.node-virtualenv/lib64/python2.7/lib-dynload/_io.so'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1103:18)
    at rimrafSync (/.../node_modules/rimraf/rimraf.js:305:17)
    at /.../node_modules/rimraf/rimraf.js:341:5
    at Array.forEach (native)
    at rmkidsSync (/.../node_modules/rimraf/rimraf.js:340:26)
    at rmdirSync (/.../node_modules/rimraf/rimraf.js:333:7)
    at rimrafSync (/.../node_modules/rimraf/rimraf.js:303:9)
    at /.../node_modules/rimraf/rimraf.js:341:5
    at Array.forEach (native)
