### ISSUE TITLE
Can't make it work on Windows 10

### ISSUE THREAD

**Issue by brunofin** [mjpizz/node-virtualenv#4]
I'm trying to make `node-virtualenv` work on Windows 10. I developed this project under a Fedora 23 installation, made a commit to a git repository and then fresh cloned it to a Windows 10 to make sure it would work. It's throwing the following error during `postinstall`:

```
> bower install && virtualenv-postinstall

Finding virtualenv 15.0.0
Downloading https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz
Unzipping https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz
Creating C:\Users\bruno\git\task-bruno-finger\.node-virtualenv
Cleaning C:/Users/bruno/git/task-bruno-finger/.node-virtualenv/.node-virtualenv-sources
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn python ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
  at child_process.js:1144:20
  at process._tickCallback (node.js:355:11)
```

I have Python 2.7 installed. In the end I have an empty `.node-virtualenv` folder in the root of my project where I should have the virtualenv installation.

Any suggestion?

**Comment by mjpizz** [comment]
Interesting! Unfortunately I don't have a Windows 10 machine offhand to test this myself. After a quick look, the error seems likely to be happening somewhere in here:

https://github.com/mjpizz/node-virtualenv/blob/master/lib/virtualenv.js#L240-L249

A few questions:

1. Does it ever report "Error while creating virtualenv" in the output?
2. The `_create` method expects your Python installation to be available as an executable named `python` in your path. Is this something like `python.exe` on Windows?
3. Looks like you're trying to use this with bower (which probably should work). Still, it's designed to be installed with npm so we should verify whether the same error happens. Can you try a sample project following the installation instructions in the [README](https://github.com/mjpizz/node-virtualenv/blob/master/README.md) to see if you get the same error?

Especially if (2) ends up being the issue, this might be a pretty quick fix. Let me know!

**Comment by brunofin** [comment]
No, it never reports "Error while creating virtualenv".

I have python 2.7 and 3.2 installed, although python 2.7 executable comes first in `PATH`. If I open a Windows Command Prompt and type `python` I get the Python 2.7 interactive shell.

I am using it with npm.

Here's the complete output of the error:

```
C:\Users\bruno\git\task-bruno-finger>npm start

> task-bruno-finger@1.0.0 prestart C:\Users\bruno\git\task-bruno-finger
> npm install


> task-bruno-finger@1.0.0 preinstall C:\Users\bruno\git\task-bruno-finger
> npm update


> task-bruno-finger@1.0.0 postinstall C:\Users\bruno\git\task-bruno-finger
> bower install && virtualenv-postinstall

Finding virtualenv 15.0.0
Downloading https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz
Unzipping https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz
Creating C:\Users\bruno\git\task-bruno-finger\.node-virtualenv
Cleaning C:/Users/bruno/git/task-bruno-finger/.node-virtualenv/.node-virtualenv-sources
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn python ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
  at child_process.js:1144:20
  at process._tickCallback (node.js:355:11)


npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! task-bruno-finger@1.0.0 postinstall: `bower install && virtualenv-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the task-bruno-finger@1.0.0 postinstall script 'bower install && virtualenv-postinstall'.
npm ERR! This is most likely a problem with the task-bruno-finger package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && virtualenv-postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls task-bruno-finger
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bruno\git\task-bruno-finger\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! task-bruno-finger@1.0.0 prestart: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the task-bruno-finger@1.0.0 prestart script 'npm install'.
npm ERR! This is most likely a problem with the task-bruno-finger package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls task-bruno-finger
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bruno\git\task-bruno-finger\npm-debug.log
```

And that's npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart task-bruno-finger@1.0.0
6 verbose unsafe-perm in lifecycle true
7 info task-bruno-finger@1.0.0 Failed to exec prestart script
8 verbose stack Error: task-bruno-finger@1.0.0 prestart: `npm install`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
8 verbose stack     at EventEmitter.emit (events.js:110:17)
8 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
8 verbose stack     at ChildProcess.emit (events.js:110:17)
8 verbose stack     at maybeClose (child_process.js:1015:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
9 verbose pkgid task-bruno-finger@1.0.0
10 verbose cwd C:\Users\bruno\git\task-bruno-finger
11 error Windows_NT 6.3.9600
12 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
13 error node v0.12.7
14 error npm  v2.11.3
15 error code ELIFECYCLE
16 error task-bruno-finger@1.0.0 prestart: `npm install`
16 error Exit status 1
17 error Failed at the task-bruno-finger@1.0.0 prestart script 'npm install'.
17 error This is most likely a problem with the task-bruno-finger package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm install
17 error You can get their info via:
17 error     npm owner ls task-bruno-finger
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]
```
If you want to check, my project is hosted at [https://gitlab.com/bruno-finger12/task-bruno-finger/tree/master](https://gitlab.com/bruno-finger12/task-bruno-finger/tree/master).
Surely I'll try the sample project, hopefully I can fix it following the instructions.

**Comment by mjpizz** [comment]
Doing a bit of research pulled up some similar issues with node-gyp. This comment has some possible things to investigate:

> 1. Make Sure Your Python and node are both x86 (32Bit) or both x86-x64 (64Bit), a mix will throw this error
2. set the environment variable PYTHON to your python.exe, in my case I ran "set PYTHON=E:\Python27\python.exe" bevore running npm

*from https://github.com/nodejs/node-gyp/issues/277#issuecomment-25943524*

Can you verify those two things on your machine?

**Comment by mjpizz** [comment]
Closing this out as inactive - let me know if you ever get a chance to give that a shot!

**Comment by RomanSaveljev** [comment]
We just hit the same issue. The root cause is that it fails to spawn python interpreter in a non-existent directory (`cwd` option). That directory is supposed to be created and populated by the `untarStream`. It does not appear.
